language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=python2.7
    - python: 3.4
      env: TOXENV=python3.4
    - python: 3.5
      env: TOXENV=python3.5
    - python: 3.6
      env: TOXENV=python3.6

os:
  - linux

install:
  - pip install setuptools --upgrade
  - pip install coveralls tox
  - pip install .

script: 
  - tox
  - python setup.py test --addopts "-v --cov pingparsing --cov-report term-missing"

after_success:
  - coveralls

notifications:
  slack:
    secure: GKve91fTPx7OIYn5zZ3X+nqy7OT9Pq7763zIPcvTqcN7ZM9C+q9LKbSk9sWGmp15fCp26Eu4/6/y9ExXmp80f3zF/caCbOlmF4o15ggLmyRb1E55NoPvMfGHz4wnlJN6wczc5/yyKMm0I0IZ5rjN5fPWaoJ4rf1huHAmIbJzS0FNH0gNFAeTDY/a+lRgHnJhSsOv/Ai+nLCL9y8Ilf83THWKW923fGA7ME+rL6t07WzKnIf71ld70eDEF+OnwYVp/7u1+Yxmo14G5Q0T/aXwhZkMTFKog6F186zBqpO+KGxLaM0q1N37DOSx4K6vKvSt60BZVJ0Wq9zUKpAIVNcYGXvj4EYouW2TFJUa1ka3ITToBT2P+/ts9N4vtlAniL4SykoaM1G2Ok8MepLyC+j38LT1ItOFi6OeDBpf5mCAaSaMQO44A6BTpIJmBk5U046GaFTHw+hQPmOyRKrCJCzzgD6RfnKB1U6kknq63lsN8SdrZAe9NcPmG3pTU+wu1uBNX+vkGYRd8bpSajxLktLBLU0DTzbmsJQqNuATe//pBHgxMJYTobjmq6L5/bgK4ePlD6sGud7JJs47G++FBCAMNoQL+X0AHTthYlDC/amlDtpPHaE415KgLR25+vf6PVgQYMyFfZyTH4ECI3zA8UM6aGmD+RyVZUHZl4lDxOreGpk=

deploy:
  provider: pypi
  user: vmmhypervisor
  password:
    secure: jwEpSFNp7smBtUvSe+NVRDJRtN4htwHE+aK2q12GHGaKtTwDfkpTHUjE5nJOgLNkmWQF/qaV2YOR3e6Oc8Gvuu6b8Z2VCuJza1xQQ2R29HthE/MNUOPq9nQy1wYY9vgYP5JVqhO5uY9r0s9zAidw3mH5HMxCVQWYAJVsK7SLE0r9DO1N05wOa3TCgi+F9c8tA5FoMkmeRDXMVA4N4HEVf4d60ZZlKTJYyEmhWYhx4SUv4zodd7p0/lTvNb+K3MUi1fcEtI4mTw+d1Hg1p5C3h6ATOeSXsENEnufokzWUQPPMk3L7ihyyvSXQnzgm7U74oJHYF5FUBNYHex+unwR1BTSal+WI6Flf6MnyPGZNV+br5lkuW6HvcF1IH1h4kw6+hNNadGvW4SyRdrCC5Qs0tw9fJ6CLfwUdamOrweLljFFKT9qNEdKHLdTPtOL2Q7MXZWvvofLm2mzQCAfrvxVywnNudcAncUvfScelGdwXW9I8PPhOSAwV0SI3A0pcngjrCnDHQkdl0UPW7hCmwVO/u0XI5scZW601YiP3SOKB5nGwP/W0N7TRxbV4lnKZeJ33FrzdfujKcz0TxT/jxrfZjV93MSRs7J2mPCFF9dE5fgNZ17iaj6uijL7t2KaokuC11rCfOzS+hpYjaussFd4DVRJ2gJJDWlSLW7DEzm53KvU=
  skip_cleanup: true
  on:
    repo: thombashi/pingparsing
    tags: true
    branch: master
    python: 3.6
  distributions: "sdist bdist_wheel"
